### ISSUE TITLE
Duplicate JavaScript dist-files on Shopware 6.5.8.5

### ISSUE THREAD

**Issue by mathiassname** [FriendsOfShopware/FroshPlatformFilterSearch#20]
### PHP Version

8.2

### Shopware Version

6.5.8.5

### Plugin Version

2.0.1

### Actual behaviour

In Shopware 6.5.8.5 the version 2.0.1 generate duplicate JavaScript dist-files.

<img width="615" alt="Bildschirmfoto 2024-02-16 um 10 01 06" src="https://github.com/FriendsOfShopware/FroshPlatformFilterSearch/assets/33735314/5a04dcfe-b772-4702-861b-e68595fb2c55">

This results in: `Uncaught Error: Plugin "FroshPlatformFilterSearch" is already registered.`

The downgrade of the plugin version to 2.0.0 works fine and don't have this issue.

### Expected behaviour

Only one file in vendor/store.shopware.com/froshplatformfiltersearch/src/Resources/app/storefront/dist/storefront

### Steps to Reproduce?

Run ./bin/build-js.sh or ./bin/build-storefront.js.

**Comment by dstammler** [comment]
same issue here, downgrade to 2.0.0 fix the issue.

**Comment by shyim** [comment]
Has been fixed with 2.0.3 release
https://github.com/shopware/github-actions/commit/a82a72a33e9bbcb3c3d4e36c5582cf34dc14f0fc

**Comment by shyim** [comment]
much more complicated than i thought, but with 2.0.4 it's 100% solved 😅
