### ISSUE TITLE
Keine Suchresultate auf mobilen Geräten

### ISSUE THREAD

**Issue by vekkon** [FriendsOfShopware/FroshPlatformFilterSearch#3]
Testen Sie dieses Problem mit einem beliebigen Mobilgerät unter der folgenden URL:
https://showcase.payrexx.com/shopware6/public/Bekleidung/

In dieser Testumgebung wurde kein Theme installiert und es existieren keine relevanten anderen Plugins.
Das Problem kann nur auf mobilen Geräten reproduziert werden (In der Mobilen Ansicht des Entwicklermodus gibt es kein Issue)

Bei der Suche nach einem Filtermerkmal werden keine Ergebnisse angezeigt, obwohl der Suchbegriff übereinstimmt.
--------------------------------------------------------------------------------------------------------------------------------------
Test this Issue with any Mobile device on the following URL:
https://showcase.payrexx.com/shopware6/public/Bekleidung/

No Theme is installed and no relevant other Plugins exist in this Test environment.
The Issue can only be reproduced on Mobile (Developermode with Mobile view has no issue)

When Searching for a filter characteristics there will show up no results although the search term matches

**Comment by tinect** [comment]
Hey @noahming do you have any example for a mobile device?
I tried to reproduce on my Galaxy S10, but the filter is working like on Desktop. 

But I can see one issue: search is just working with lowercase texts.
![image](https://user-images.githubusercontent.com/135993/90988368-8d7d3380-e592-11ea-85ca-3ff40cd3e735.png)

![image](https://user-images.githubusercontent.com/135993/90988374-966e0500-e592-11ea-94f0-3a04712929b2.png)

**Comment by vekkon** [comment]
You were right @tinect the only issue was, that it won't find anything with an uppercase letter.
I only had this issue on mobile because my phone writes the first letter in uppercase.

Thanks for fixing, looking forward to the update

**Comment by tinect** [comment]
Hey @noahming Update is now published.
